"use client"
import {ListingGrid} from "@/components/market/listings/listing-grid";
import {Listing} from "@/types/Listing";


const MOCK_LISTINGS: Listing[] = [
    {
        id: "1",
        price: 125.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "MT",
        foiling: "GF",
        set: "Welcome to Rathe",
        cardName: "Ira1",
        sellerName: "Yahel",
        sellerPhoneNumber: "972543042596",
        sellerDiscord: "Dusk",
    },
    {
        id: "2",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "NM",
        foiling: "CF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "3",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "EX",
        foiling: "RF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "4",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "GD",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "5",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "LP",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "6",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "PL",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "7",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "PO",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "8",
        price: 125.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "MT",
        foiling: "GF",
        set: "Welcome to Rathe",
        cardName: "Ira1",
        sellerName: "Yahel",
        sellerPhoneNumber: "972543042596",
        sellerDiscord: "Dusk",
    },
    {
        id: "9",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "NM",
        foiling: "CF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "10",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "EX",
        foiling: "RF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "11",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "GD",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "12",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "LP",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "13",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "PL",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "14",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "PO",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "15",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "GD",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "16",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "LP",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "17",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "PL",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },
    {
        id: "18",
        price: 450.00,
        image: "/cards/IRA001-P_EUmBrk0.width-450.webp",
        condition: "PO",
        foiling: "NF",
        set: "Monarch",
        cardName: "Command and Conquer",
        sellerName: "Dudu",
        sellerPhoneNumber: "972522260702",
        sellerDiscord: "HolySrulink",
    },

];

export default function HomePage() {
    return (
        <>
            <ListingGrid listings={MOCK_LISTINGS} />
        </>
    )
}

